# 网站信息
site_name: MHFramework
# site_url: 
site_author: zlykernel

# github 仓库信息
repo_name: mhf-doc
repo_url: https://github.com/MurrayHillFreedom/mhf-doc

# 版权信息
copyright: Copyright &copy; 2021-present <a href="https://github.com/MurrayHillFreedom" target="_blank" rel="noopener noreferrer">MurrayHillFreedom</a>

# 主题
theme:
  name: material
  language: zh
  static_templates:
    - 404.html
  features:
    - header.autohide
    # 导航设置
    # - navigation.instant
    # 导航栏展开
    - navigation.expand
    # - navigation.sections
    - navigation.tracking
    # 导航编程tab页(横向)
    # - navigation.tabs
    # - navigation.tabs.sticky
    # - navigation.top
    # - navigation.indexes
    # 搜索高亮
    - search.highlight
    # 搜索分享
    - search.share
    # 搜索建议
    - search.suggest
    # - toc.integrate
    - content.code.annotate
  # 
  palette:
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: light blue
      accent: deep purple
      toggle:
        icon: material/weather-sunny
        name: Switch to dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: cyan
      accent: deep purple
      toggle:
        icon: material/weather-night
        name: Switch to light mode  
  font:
    text: Roboto
    code: Roboto Mono
  icon:
    repo: fontawesome/brands/github

  # 自定目录 覆写模板
  custom_dir: overrides
# 
markdown_extensions:
  - attr_list
  - md_in_html

# 插件
plugins:
  - search:
      lang: ja
  # 在文档最后添加markdown的最后修改时间 pip install mkdocs-git-revision-date-localized-plugin
  - git-revision-date-localized
  - minify:
      minify_html: true

extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/MurrayHillFreedom/mhf-doc
  analytics:
    provider: google
    property: G-KJB4RXSKZG
  
# 导航
nav:
  - 什么是MHF: "1-前言/什么是MHF&&简介.md"
  - 关于作者: "1-前言/关于作者.md"
  - 如何阅读本文档: "1-前言/如何阅读本文档.md"
  - 架构篇:
    - 方法论: "2-架构篇/方法论.md"
  - 基础框架篇: 
    - 本章整体说明 : "3-基础框架篇/本章整体说明.md"
  - 功能模块篇: 
    - 本章整体说明 : "4-功能模块篇/本章整体说明.md"
    - 用户模块 : "4-功能模块篇/用户模块.md"
  - 最佳实践篇: ""
  - 后记: ""
   